In [1]:
import numpy as np

In [2]:
print(np.random.rand)

<built-in method rand of mtrand.RandomState object at 0x0000005988A910B8>


In [4]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and propagate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]

In [7]:
np.random.rand()

0.6901996060069633

In [10]:
6*np.random.rand() + 1

5.192224170394064

In [15]:
int( 6*np.random.rand() + 1)

4

In [13]:
int(3.999)

3

In [16]:
np.random.rand(6)

array([ 0.47403923,  0.33270845,  0.51772856,  0.05501387,  0.23022263,
        0.87286646])

In [21]:
(6*np.random.rand(6) + 1 ).astype(int)

array([6, 3, 6, 3, 5, 4])

In [22]:
np.unique( (6*np.random.rand(6) + 1 ).astype(int) )

array([3, 4, 5, 6])

In [23]:
np.unique( (6*np.random.rand(600) + 1 ).astype(int) )

array([1, 2, 3, 4, 5, 6])

In [24]:
np.unique( (6*np.random.rand(6000) + 1 ).astype(int) )

array([1, 2, 3, 4, 5, 6])

In [30]:
support = np.unique( (6*np.random.rand(10000) + 1 ).astype(int), return_counts=True )

In [31]:
print(support)

(array([1, 2, 3, 4, 5, 6]), array([1598, 1715, 1619, 1659, 1737, 1672], dtype=int64))


In [32]:
dict(zip(support[0], support[1]))

{1: 1598, 2: 1715, 3: 1619, 4: 1659, 5: 1737, 6: 1672}

In [33]:
dict(zip(support[0], support[1]/np.sum(support[1])))

{1: 0.1598,
 2: 0.17150000000000001,
 3: 0.16189999999999999,
 4: 0.16589999999999999,
 5: 0.17369999999999999,
 6: 0.16719999999999999}